[workspace]
resolver = "2"
members = ["beeper-axum", "example"]

[workspace.package]
license = "GPL-3.0"
authors = [
    "lerboe <mail@laurinbrandner.ch>",
]
repository = "https://github.com/lerboe/beeper-axum"
readme = "README.md"
keywords = ["ebpf", "bpf", "libbpf", "l7", "http"]
description = "Application-Layer Parsing in eBPF"
categories = ["network-programming"]

[patch.crates-io]
h2 = { path = "../h2" }
